apiVersion: v1
kind: Secret
metadata:
  name: castflow-secrets
  namespace: castflow
type: Opaque
stringData:
  jwt-secret: "change-this-in-production-use-openssl-rand-hex-32"
  icecast-source-password: "hackme-source-change-me"
  icecast-admin-password: "hackme-admin-change-me"
  icecast-password: "hackme-change-me"
