apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radio-music-pvc
  namespace: castflow
spec:
  # 採用 ReadWriteOnce 完美適配 local-path 及單節點存儲，同節點多 Pod (server 與 gateway/liquidsoap) 可共同掛載
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radio-data-pvc
  namespace: castflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radio-backups-pvc
  namespace: castflow
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
