apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radio-music-pvc
  namespace: castflow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radio-hls-pvc
  namespace: castflow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi